export const SET_FETCHING_IN_PROCESS = "POKEMONS/SET_FETCHING_IN_PROCESS";
export const POKEMONS_SET_POKEMONS = "POKEMONS/SET_POKEMONS";
export const POKEMONS_SET_NEXT_CHUNK = "POKEMONS/SET_NEXT_CHUNK";
export const POKEMONS_SET_IS_SELECTED = "POKEMONS/SET_IS_SELECTED";
export const POKEMONS_SET_SELECTED = "POKEMONS/SET_SELECTED";
export const TYPES_FILTER_SET_TYPE = "TYPES_FILTER/SET_TYPE";
export const TYPES_FILTER_SET_IS_OPEN = "TYPES_FILTER/SET_IS_OPEN";
